[package]
name = "brass_Browser"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.29"
servo = { git = "https://github.com/servo/servo", branch = "main" }
log = "0.4"
env_logger = "0.10"

# Warstwa interfejsu użytkownika
egui = "0.27"
egui-winit = "0.27"
eframe = { version = "0.27", features = ["glow"] }
glow = "0.13"
dpi = "0.1" # Dodane dla PhysicalSize